<?php

namespace Tony\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\Null;


/**
 * UserSocialLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSocialLinkRepository extends EntityRepository
{




}
