<?php

namespace Tony\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getCompanyComments($companyId, $approved = true)
    {
        $qc = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.company = :company_id')
            ->addOrderBy('c.created')
            ->setParameter('company_id', $companyId);

        if (false === is_null($approved))
            $qc->andWhere('c.approved = :approved')
                ->setParameter('approved', $approved);

        return $qc->getQuery()
            ->getResult();
    }

    public function getLatestComments($limit = 10)
    {
        $qc = $this->createQueryBuilder('c')
            ->select('c')
            ->addOrderBy('c.id', 'DESC');

        if (false === is_null($limit))
            $qc->setMaxResults($limit);

        return $qc->getQuery()
            ->getResult();
    }
}
