<?php

namespace Tony\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{
    public function getLatestLists($limit = null)
    {
        $qc = $this->createQueryBuilder('C')
            ->select('C')
            ->addOrderBy('C.created', 'DESC');

        if (false === is_null($limit))
            $qc->setMaxResults($limit);

        return $qc->getQuery()
            ->getResult();
    }

}
